apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: platforme-etude
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: CHANGE_ME_POSTGRES_PASSWORD
  JWT_SECRET: CHANGE_ME_WITH_A_LONG_RANDOM_JWT_SECRET
  SPRING_MAIL_USERNAME: CHANGE_ME_MAIL_USERNAME
  SPRING_MAIL_PASSWORD: CHANGE_ME_MAIL_APP_PASSWORD
